/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VISTA;

import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class PrincipalJF extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalJF
     */
    public PrincipalJF() {
        initComponents();
        this.setResizable(false); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Escritorio = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        shcSalir = new javax.swing.JMenuItem();
        Pacientes = new javax.swing.JMenu();
        shcRegistrar = new javax.swing.JMenuItem();
        shcConsultar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Escritorio.setBackground(new java.awt.Color(204, 204, 204));
        Escritorio.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Escritorio.setName("GESTION DE CITAS"); // NOI18N

        javax.swing.GroupLayout EscritorioLayout = new javax.swing.GroupLayout(Escritorio);
        Escritorio.setLayout(EscritorioLayout);
        EscritorioLayout.setHorizontalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 575, Short.MAX_VALUE)
        );
        EscritorioLayout.setVerticalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 452, Short.MAX_VALUE)
        );

        fileMenu.setMnemonic('f');
        fileMenu.setText("Archivo");

        shcSalir.setMnemonic('x');
        shcSalir.setText("Salir");
        shcSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shcSalirActionPerformed(evt);
            }
        });
        fileMenu.add(shcSalir);

        menuBar.add(fileMenu);

        Pacientes.setMnemonic('e');
        Pacientes.setText("Pacientes");

        shcRegistrar.setMnemonic('t');
        shcRegistrar.setText("Registrar");
        shcRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shcRegistrarActionPerformed(evt);
            }
        });
        Pacientes.add(shcRegistrar);

        shcConsultar.setMnemonic('y');
        shcConsultar.setText("Consultar");
        Pacientes.add(shcConsultar);

        menuBar.add(Pacientes);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio)
        );

        Escritorio.getAccessibleContext().setAccessibleName("GESTION DE CITAS");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void shcSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shcSalirActionPerformed
        int r= JOptionPane.showOptionDialog(this, "Está seguro de salir...?", 
                "ATENCIÓN", 
                JOptionPane.YES_OPTION, 
                JOptionPane.QUESTION_MESSAGE, null, null, null);
        if (r==0){
            System.exit(0);
        }
    }//GEN-LAST:event_shcSalirActionPerformed

    private void shcRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shcRegistrarActionPerformed
        // TODO add your handling code here:
        
        //Instancias
        RegPacienteInternalFrame r1= new RegPacienteInternalFrame();
        Escritorio.add(r1);
        r1.show();
        
        ConsPacienteInternalFrame c1= new ConsPacienteInternalFrame();
        Escritorio.add(c1);
        c1.show();
        
        
        
        
    }//GEN-LAST:event_shcRegistrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalJF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Escritorio;
    private javax.swing.JMenu Pacientes;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem shcConsultar;
    private javax.swing.JMenuItem shcRegistrar;
    private javax.swing.JMenuItem shcSalir;
    // End of variables declaration//GEN-END:variables

}
