/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Clases.ConexionBD;
import java.security.Principal;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.util.logging.*;
import javax.swing.table.*;

/**
 *
 * @author Usuario
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        Crear_Modelo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cbTD = new javax.swing.JComboBox<>();
        txtDocumento = new javax.swing.JTextField();
        txtNombres = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtHora = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMotivo = new javax.swing.JTextArea();
        btnGuardar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        txtFecha = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        Tabla_Registros = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("GESTIÓN DE INGRESO- ESTABLECIMIENTO COMERCIAL");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 20, -1, -1));

        jLabel2.setText("TD:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 76, -1, -1));

        jLabel3.setText("Documento:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 109, -1, -1));

        jLabel4.setText("Nombres:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 147, -1, -1));

        jLabel5.setText("Apellidos:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 185, -1, -1));

        jLabel6.setText("Teléfono:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 223, -1, -1));

        jLabel7.setText("Dirección:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 261, -1, -1));

        jLabel8.setText("Fecha de ingreso:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 304, -1, -1));

        jLabel9.setText("Hora de ingreso:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 347, -1, -1));

        jLabel10.setText("Motivo:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 385, -1, -1));

        cbTD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TI", "CC", "CE" }));
        getContentPane().add(cbTD, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, -1, -1));
        getContentPane().add(txtDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 109, 144, 27));
        getContentPane().add(txtNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 147, 145, 27));
        getContentPane().add(txtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 185, 145, 27));
        getContentPane().add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 223, 145, 27));
        getContentPane().add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 261, 145, 27));

        txtHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHoraActionPerformed(evt);
            }
        });
        getContentPane().add(txtHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 334, 100, 27));

        txtMotivo.setColumns(20);
        txtMotivo.setRows(5);
        jScrollPane1.setViewportView(txtMotivo);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 372, 230, 105));

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 495, -1, -1));

        btnLimpiar.setText("Limpiar");
        getContentPane().add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 495, -1, -1));

        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });
        getContentPane().add(btnConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(792, 72, -1, -1));

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(476, 72, -1, -1));

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(644, 72, -1, -1));

        txtFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaActionPerformed(evt);
            }
        });
        getContentPane().add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 296, 120, 30));

        Tabla_Registros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(Tabla_Registros);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(436, 109, 493, 368));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoraActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
     
        ConexionBD con= new ConexionBD();
        con.conectarBD();
        String TD= cbTD.getSelectedItem().toString();
        String doc= txtDocumento.getText();
        String nom= txtNombres.getText();
        String ape= txtApellidos.getText();
        String tel= txtTelefono.getText();
        String dir= txtDireccion.getText();
        String fec= txtFecha.getText();
        String hor= txtHora.getText();
        String motiv= txtMotivo.getText();
        if (!doc.isEmpty()){
            if (!nom.isEmpty()){
                if (!ape.isEmpty()){
                    if (!tel.isEmpty()){
                        if (!dir.isEmpty()){
                            if (!fec.isEmpty()){
                                if (!hor.isEmpty()){
                                    if (!motiv.isEmpty()){
                                        try{
                                            String SQL= "INSERT INTO personas"
                                                    + "(td,identificacion,nombre,apellidos,telefono,direccion,fecha_ing,hora_ing,motivo)"
                                                    + "VALUES"
                                                    +"('"+TD+"','"+doc+"','"+nom+"','"+ape+"','"+tel+"','"+dir+"','"+fec+"','"+hor+"','"+motiv+"');";
                                            con.sentencia.execute(SQL);
                                            JOptionPane.showMessageDialog(null, ",Los datos fueron guardados con éxito!");
                                        } catch (SQLException ex){
                                            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE,null,ex);
                                        }
                                } else{
                                        JOptionPane.showMessageDialog(null, "Por favor ingrese el motivo de ingreso");
                                    }
                            } else{
                                    JOptionPane.showMessageDialog(null, "Por favor ingrese la hora de ingreso");
                                }
                        } else{
                                JOptionPane.showMessageDialog(null, "Por favor digite la fecha de ingreso");
                            }
                    } else{
                            JOptionPane.showMessageDialog(null, "Por favor ingrese la dirección");
                        }
                } else{
                        JOptionPane.showMessageDialog(null, "Por favor ingrese el teléfono");
                    }
            } else{
                    JOptionPane.showMessageDialog(null, "Por favor ingrese el apellido");
                }
        } else{
                JOptionPane.showMessageDialog(null, "Por favor ingrese el nombre");
            }
    } else{
            JOptionPane.showMessageDialog(null, "Por favor ingrese el documento");
        }
        con.DesconectarBD();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        // TODO add your handling code here:
        Consultar();
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        String ID= Tabla_Registros.getValueAt(Tabla_Registros.getSelectedRow(),0).toString();
        String td= Tabla_Registros.getValueAt(Tabla_Registros.getSelectedRow(),1).toString();
        String doc= Tabla_Registros.getValueAt(Tabla_Registros.getSelectedRow(),2).toString();
        String nom= Tabla_Registros.getValueAt(Tabla_Registros.getSelectedRow(),3).toString();
        String ape= Tabla_Registros.getValueAt(Tabla_Registros.getSelectedRow(),4).toString();
        String tel= Tabla_Registros.getValueAt(Tabla_Registros.getSelectedRow(),5).toString();
        String dir= Tabla_Registros.getValueAt(Tabla_Registros.getSelectedRow(),6).toString();
        String fech= Tabla_Registros.getValueAt(Tabla_Registros.getSelectedRow(),7).toString();
        String hora= Tabla_Registros.getValueAt(Tabla_Registros.getSelectedRow(),8).toString();
        String mot= Tabla_Registros.getValueAt(Tabla_Registros.getSelectedRow(),9).toString();
        
        Actualizar Act= new Actualizar(null, true);
        Act.AtxtID.setText(ID);
        Act.AcbTD.setSelectedItem(td);
        Act.AtxtNombres.setText(nom);
        Act.AtxtApellidos.setText(ape);
        Act.AtxtTelefono.setText(tel);
        Act.AtxtDireccion.setText(dir);
        Act.AtxtFechaI.setText(fech);
        Act.AtxtHoraI.setText(hora);
        Act.AtxtMotivo.setText(mot);
        Act.setVisible(true);
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        
        try{
            String ID= Tabla_Registros.getValueAt(Tabla_Registros.getSelectedRow(),0).toString();
            ConexionBD con= new ConexionBD();
            con.conectarBD();
            String SQL= "DELETE FROM personas WHERE id='"+ID+"'";
            con.sentencia.execute(SQL);
            JOptionPane.showMessageDialog(null,"¡El registro fue eliminado!");
            con.DesconectarBD();
        } catch (SQLException ex){
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    DefaulTableModel modelo;
    private void Crear_Modelo(){
        try{
            modelo= (new DefaultTableModel(
                    null, new String[]{
                        "TD","Documento","Nombres",
                        "Apellidos", "Teléfono", 
                        "Dirección", "Fecha", "Hora",
                        "Motivo"}){
                Class[] types= new Class[]{
                    java.lang.String.class,java.lang.String.class,
                    java.lang.String.class,java.lang.String.class,
                    java.lang.String.class,java.lang.String.class,
                    java.lang.String.class,java.lang.String.class,
                    java.lang.String.class
                };
                boolean[] canEdit= new boolean[]{
                    false,false,false,false,false,false,false,false,false
                };
                public Class getColumnClass(int columnIndex){
                    return types[columnIndex];
                }
                public boolean isCellEditable(int rowIndex, int colIndex){
                    return canEdit[colIndex];
                }
            });
            Tabla_Registros.setModel(modelo);
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e.toString() + "ERROR");
        }
    }
    
    private void Consultar(){
        try{
            int i= 0; Object ob[]= null;
            ConexionBD con= new ConexionBD();
            con.conectarBD();
            String SQL= "SELECT * FROM personas";
            con.resultado= con.sentencia.executeQuery(SQL);
            modelo.setRowCount(0);  
            while (con.resultado.next()) {
                modelo.addRow(ob);
                modelo.setValueAt(con.resultado.getString("td"),i,0);
                modelo.setValueAt(con.resultado.getString("identificacion"),i,1);
                modelo.setValueAt(con.resultado.getString("nombre"),i,2);
                modelo.setValueAt(con.resultado.getString("apellido"),i,3);
                modelo.setValueAt(con.resultado.getString("telefono"),i,4);
                modelo.setValueAt(con.resultado.getString("direccion"),i,5);
                modelo.setValueAt(con.resultado.getString("fecha_ing"),i,6);
                modelo.setValueAt(con.resultado.getString("hora_ing"),i,7);
                modelo.setValueAt(con.resultado.getString("motivo"),i,8);
                i++;
            }
            con.DesconectarBD();
        } catch (SQLException ex){
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabla_Registros;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JComboBox<String> cbTD;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtDocumento;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtHora;
    private javax.swing.JTextArea txtMotivo;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables

    
}
